@startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "class bid.models"{
  
  interface "IBid" {
    + id :string
    + projectId :string
    + freelancerId :string
    + message :string
    + amount :number
  }
  hide IBid  methods

  class "BidActions"{  
  + placeBid()
  + getByProject()
  + choose() 
  <<property>>
   + id :string
    + projectId :string
    + freelancerId :string
    + message :string
    + amount :number
  
  }
class "Bid" <<Component>> {
	+ getEmail()
  + useEffect()
  <<property>>
   + id :string
    + projectId :string
    + freelancerId :string
    + message :string
    + amount :number
}

hide Bid circle
show Bid fields

class "OpenProjectChooseBid" <<Component>>  {
	+ chooseFreelancer()
  + useEffect()
  + renderBids()
  <<property>>
   + id :string
    + projectId :string
    + freelancerId :string
    + message :string
    + amount :number
}

hide OpenProjectChooseBid circle
show OpenProjectChooseBid fields

class "OpenProjectBid" <<Component>> {
	+ OpenProjectBid()
  <<property>>
   + id :string
    + projectId :string
    + freelancerId :string
    + message :string
    + amount :number
}

hide OpenProjectBid circle
show OpenProjectBid fields

  
class "BiddingService" {
	+ post()
  + getByProjectId()
  + chooseFreelancer()
  <<property>>
   + id :string
    + projectId :string
    + freelancerId :string
    + message :string
    + amount :number
}

  IBid <|.. Bid 
  IBid <|.. OpenProjectChooseBid
  IBid <|.. BidActions 
  IBid <|.. OpenProjectBid
  IBid <|.. BiddingService 
  IBid <|.. BiddingService
  

}


@enduml