@startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "message.models"{
  
  interface "IMessage" {
    + id :string
    + senderId :string
    + receiverId :string
    + contactId :string
    + timestamp :number
  }
  hide IMessage  methods

  

class "Chat" <<Component>>{
  <<property>>
   + id :string
    + senderId :string
    + receiverId :string
    + contactId :string
    + timestamp :number
}
hide Chat circle

class "MessageInputs" <<Component>>{
  + sendEvent()
  <<property>>
    + id :string
    + senderId :string
    + receiverId :string
    + contactId :string
    + timestamp :number
}
hide MessageInputs circle

  
class "ReceivingMessage" <<Component>>{
  <<property>>
    + id :string
    + senderId :string
    + receiverId :string
    + contactId :string
    + timestamp :number
}
hide ReceivingMessage circle
  
  
class "SendMessage" <<Component>>{
  <<property>>
    + id :string
    + senderId :string
    + receiverId :string
    + contactId :string
    + timestamp :number
}
hide SendMessage circle
  
class "MessageActions" {
  + sendMessage() :IMessage
  + getMessages() :string
  <<property>>
    + id :string
    + senderId :string
    + receiverId :string
    + contactId :string
    + timestamp :number
}

class "MessageService" {
  + post() :IMessage
  + get() :string
  <<property>>
    + id :string
    + senderId :string
    + receiverId :string
    + contactId :string
    + timestamp :number
}
  
  IMessage <|.. MessageInputs 
  IMessage <|.. Chat
   IMessage <|.. ReceivingMessage
   IMessage <|.. SendMessage
  IMessage <|.. MessageActions
  IMessage <|.. MessageService

}


@enduml