@startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "profile.models"{
  
  interface "IProfile" {
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
  }
  hide IProfile  methods

  

class "Contact" {
  + useEffect()
  <<property>>
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
}
hide Contact circle

class "EditProfileContent" {
  + useEffect()
  + getUser() :string
  + handleFileUpload()
  + createProfile()
  + saveChanges()
  + dispatch()
  <<property>>
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
}
hide EditProfileContent circle

class "ProfileAvatar" {
  <<property>>
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
}
hide ProfileAvatar circle

class "ProfileRating" {
  <<property>>
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
}
hide ProfileRating circle
  
class "ProfileExperience" {
  <<property>>
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
}
hide ProfileExperience circle

  
class "ProfileSkills" {
  <<property>>
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
}
hide ProfileSkills circle
  
class "ProfileTitle" {
  <<property>>
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
}
hide ProfileTitle circle
  
class "OpenProjectContent" {
  <<property>>
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
}
hide OpenProjectContent circle

class "ProfileActions" {
  + getByUserId() :string
  + create() :IProfile
  + update() :IProfile
  <<property>>
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
}

class "ProfileService" {
  + getByUserId() :string
  + create() :IProfile
  + update() :IProfile
  <<property>>
    + id :string
    + userId :string
    + profilePictureUrl :string
    + rating :number
    + title :string
    + description? :string
    + skills :string[]
    + experience :string[]
}
  

  IProfile <|.. Contact 
  IProfile <|.. EditProfileContent
  IProfile <|.. ProfileAvatar 
  IProfile <|.. ProfileRating
  IProfile <|.. ProfileExperience 
  IProfile <|.. ProfileSkills
  IProfile <|.. ProfileTitle 
  IProfile <|.. OpenProjectContent
  IProfile <|.. ProfileActions 
  IProfile <|.. ProfileService
  
}


@enduml