@startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "user.models"{
  
  interface "IUser" {
    + id :string
    + firstName :string
    + lastName :string
    + email :string
    
  }
  hide IUser  methods

class "Contact" <<Component>>{
  <<property>>
    + id :string
    + firstName :string
    + lastName :string
    + email :string
   

}
   hide Contact  circle

class "EventFile" <<Component>>{
  <<property>>
    + id :string
    + firstName :string
    + lastName :string
    + email :string
}
   hide EventFile  circle
  
class "EventMessage" <<Component>>{
  <<property>>
    + id :string
    + firstName :string
    + lastName :string
    + email :string
}
   hide EventMessage  circle
  
class "EditProfileContent" <<Component>>{
  <<property>>
    + id :string
    + firstName :string
    + lastName :string
    + email :string
}
   hide EditProfileContent  circle
  
class "ProfileRating" <<Component>>{
  <<property>>
    + id :string
    + firstName :string
    + lastName :string
    + email :string
}
   hide ProfileRating  circle  
 
class "profileContent" <<Component>>{
  <<property>>
    + id :string
    + firstName :string
    + lastName :string
    + email :string
}
   hide profileContent  circle  
  
class "ProfileName" <<Component>>{
  <<property>>
    + id :string
    + firstName :string
    + lastName :string
    + email :string
}
   hide ProfileName  circle  

class "Bid" <<Component>>{
  <<property>>
    + id :string
    + firstName :string
    + lastName :string
    + email :string
}
   hide Bid  circle  
  
class "ProfileIntro" <<Component>>{
  <<property>>
    + id :string
    + firstName :string
    + lastName :string
    + email :string
}
   hide ProfileIntro  circle  
  
class "UserService" {
  + getByUserId() :string
  <<property>>
    + id :string
    + firstName :string
    + lastName :string
    + email :string
}
 
  IUser <|.. Contact 
  IUser <|.. EventFile
  IUser <|.. EventMessage 
  IUser <|.. EditProfileContent
  IUser <|.. ProfileRating 
  IUser <|.. profileContent
  IUser <|.. ProfileName 
  IUser <|.. Bid
  IUser <|.. ProfileIntro 
  IUser <|.. UserService
  
  
}


@enduml