@startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "class Views"{
  
rectangle "Profile view" <<Content Page>>
rectangle "_app view" <<Content Page>>
rectangle "_document view" <<Content Page>>
rectangle "Project view" <<Content Page>>
rectangle "Projects view" <<Content Page>>
rectangle "about view" <<Content Page>>
rectangle "account view" <<Content Page>>
rectangle "Categories view" <<Content Page>>
rectangle "Chat view" <<Content Page>>
rectangle "dashboard view" <<Content Page>>
rectangle "employer view" <<Content Page>>
rectangle "forgot-password view" <<Content Page>>
rectangle "freelancer view" <<Content Page>>
rectangle "GDPR view" <<Content Page>>
rectangle "Home view" <<Content Page>>
rectangle "login view" <<Content Page>>
rectangle "privacy-policy view" <<Content Page>>
rectangle "sign-up view" <<Content Page>>
rectangle "terms-of-use view" <<Content Page>>
  
  
}


@enduml