
@startuml
skinparam rectangle {
	roundCorner 25
  
}
package "Converge workflows" {
rectangle "Higher order React component" as Converge {
	rectangle "User interface \n React component" as sa 
}

rectangle "Service End Points" as service   {
	rectangle "Services" 
}

rectangle "Redux store" as redux{
	rectangle "Reducers"
  rectangle "Middleware"

}


rectangle "Request Module" as request
rectangle "Action" as action
rectangle "New State" as newState
rectangle "Http request" as http
rectangle "Http response" as response


sa --> request
sa --> action
request --> http
http --> service
service -up-> response
response -up-> redux
action --> redux
redux -up-> newState
newState -up-> Converge
}
@enduml