@startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "class Action"{
  

class "BidActions" {
  + placeBid() :IBid
  + getByProject() :string
  + choose() :IBid
}

class "CollaborationActions" {
  + send(content: any, projectId: string, type: string) 
  + getByProjectId() :string
}

class "ContactActions" {
  + getContacts() :string
  + addContact() :string
  + setCurrentContact() :string
}


class "MessageActions" {
  + sendMessage() :IMessage
  + getMessages() :string
}

class "PaymentActions" {
  + accountExists() :IMessage
}


class "ProfileActions" {
  + getByUserId() :string
  + create() :IProfile
  + update() :IProfile
}

class "ProjectActions" {
  + getByUserId() :string
  + createProject() :IProject
  + get()
  + getOpen()
  + getById() :string
}
  
class "SubmitActions" {
  + setSubmitting() :boolean
  + wasFailure() :string
}
  
  
class "UserActions" {
  + login(email: string, password: string)
  + signUp(email: string, password: string, confirmPassword: string, firstName: string, lastName: string,) :IProfile
  + logout()
}
  
  
}


@enduml