@startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "class authentication.reducers"{
  
class "Authentication" {
  + authentication(state, action)
} 
  
}


@enduml