@startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "class bidding.reducers"{
  
class "Bidding" {
  + postBidRequest(state, action)
  + getByProjectId(state, action)
  + chooseFreelancer(state, action)
}
}


@enduml