@startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "class profile.reducers"{
  
class "Profile" {
  + getByUserId(state, action)
  + createProfile(state, action)
  + updateProfile(state, action)
}
  
  
}


@enduml