@startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "class submitting.reducers"{
  
class "Submitting" {
  + submitting(state, action)
}  
  
}


@enduml