pakke diagram

@startuml

 skinparam monochrome true
 top to bottom direction

package "pkg Converge Classes"{
  
  package "Converge"{
   package Services[
     <&folder> + authentication.service 
     <&folder> + bidding.service 
     <&folder> + category.service
     <&folder> + collaboration.service
     <&folder> + contacts.service
     <&folder> + message.service 
     <&folder> + payments.service 
     <&folder> + profile.service 
     <&folder> + project.service 
     <&folder> + user.service 
     <&folder> + files.service 
  ]
  
   package Action[
    <&spreadsheet> + alert.actions
    <&spreadsheet> + bid.actions
    <&spreadsheet> + collaboration.actions
    <&spreadsheet> + contacts.actions
    <&spreadsheet> + message.actions
    <&spreadsheet> + payments.actions
    <&spreadsheet> + project.actions
    <&spreadsheet> + profile.actions
    <&spreadsheet> + submit.actions
    <&spreadsheet> + user.actions
  ]

 package Constants[
    <&spreadsheet> + alert.constants
    <&spreadsheet> + bid.constants
    <&spreadsheet> + collaboration.constants
    <&spreadsheet> + contacts.constants
    <&spreadsheet> + message.constants
    <&spreadsheet> + payments.constants
    <&spreadsheet> + project.constants
    <&spreadsheet> + profile.constants
    <&spreadsheet> + submit.constants
    <&spreadsheet> + user.constants

  ]

 package Models[
    <&folder>  + bid.models
    <&folder>  + category.models
    <&folder>  + contact.models
    <&folder>  + deposit.models
    <&folder>  + event.models
    <&folder>  + message.models
    <&folder>  + payment.models
    <&folder>  + profile.models
    <&folder>  + project.models
    <&folder>  + subcategory.models
    <&folder>  + transaction.models
    <&folder>  + user.authentication.models
    <&folder>  + user.models
    <&folder>  + withdraw.models
]
   package Reducers[
  <&spreadsheet> + alert.reducer
  <&spreadsheet> + bidding.reducer
  <&spreadsheet> + category.reducer
  <&spreadsheet> + collaboration.reducer
  <&spreadsheet> + contacts.reducer
  <&spreadsheet> + message.reducer
  <&spreadsheet> + payments.reducer
  <&spreadsheet> + profile.reducer
  <&spreadsheet> + project.reducer
  <&spreadsheet> + user.reducer

  ]
 
  package Views[
     <&folder> + profile
     <&folder> + project
     <&folder> + projects
     <&spreadsheet> + _app
     <&spreadsheet> + _document
     <&spreadsheet> + about
     <&spreadsheet> + about
     <&spreadsheet> + account
     <&spreadsheet> + categories
     <&spreadsheet> + chat
     <&spreadsheet> + dashboard
     <&spreadsheet> + employer
     <&spreadsheet> + forgot-password
     <&spreadsheet> + freelancer
     <&spreadsheet> + GDPR
     <&spreadsheet> + index
     <&spreadsheet> + login
     <&spreadsheet> + privacy-policy
     <&spreadsheet> + sign-up
     <&spreadsheet> + terms-of-use
  ]
  
     package Helpers[
   <&spreadsheet> + auth.headers
]
    }
  }


@enduml