  @startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "authentication.service"{
  
interface "IUserAuthentication" {
    + id :string
    + token :string
    + email :string
    
  }
  hide IUserAuthentication  methods
  
class AuthenticationService{
  + login(email: string, password: string)
  + signUp( email: string, password: string, firstName: string, lastName: string)
  + logout() :void
  + isLoggedIn() :boolean
  + getToken() :string
  + getId() :string

}
 IUserAuthentication <|.. AuthenticationService
  
  
}


@enduml