  @startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "bidding.service"{
  
  interface "IBid" {
    + id :string
    + projectId :string
    + freelancerId :string
    + message :string
    + amount :number
  }
  hide IBid  methods
  
class BiddingService{
  + post(bid: IBid)
  + chooseFreelancer(bid: IBid)


}
 IBid <|.. BiddingService
  
  
}


@enduml