  @startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "category.service"{
  
 interface "ICategory" {
    + label :string
    + value : string
    + subCategories :ISubCategory[ ]
    
  }
  hide ICategory  methods
  
class CategoryService{
  + getSubCategoriesSorted(categoryName: string)
  + getAll()
  + getAllSorted()
  + getSubCategories(categoryName: string)
  + getCapilatized(name: string)
  + getByCategoryAndString(categoryValue: string, subString: string) 


}
 ICategory <|.. CategoryService
  
  
}


@enduml