  @startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "payments.service"{
  
  
class PaymentsService{
  + accountExists(userId: string) 
  + createStripeAccount(code: string)
  + withdraw(amount: number)
  + getToken(amount: number)
  +  getBalance()
  +  getTransactions()

}

  
}


@enduml