  @startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "project.service"{
  
interface "IProject" {
   + id :string
   + ownerId :string
   + freelancerId :string
   + projectContent:[ 
       + title :string
       + description :string
       + category :string
       + subCategory :string
       + amount :number
       + files :string[]
    ]
  }
  hide IProject  methods
  
class ProjectService{
  + create(values: IProject)
  + get()
  + getById(projectId: string)
  + getOpen()
  + getByUserId(userId: string)

}

  IProject <|.. ProjectService
  
}


@enduml