  @startuml

 skinparam monochrome true
 skinparam classAttributeIconSize 0
 top to bottom direction
package "user.service"{
  
interface "IUser" {
    + id :string
    + firstName :string
    + lastName :string
    + email :string
    
  }
  hide IUser  methods

  
class UserService{
  + getByUserId(userId: string)

}

  IUser <|.. UserService
  
}


@enduml